# Generated by Django 4.1.7 on 2023-03-06 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='created',
        ),
        migrations.AddField(
            model_name='task',
            name='deadline',
            field=models.DateField(default='2023-12-31'),
        ),
    ]
